"""Update

Revision ID: 550cf8392203
Revises: 2d694b4b6578
Create Date: 2024-07-12 17:21:10.456249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550cf8392203'
down_revision = '2d694b4b6578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_tag', schema=None) as batch_op:
        batch_op.alter_column('user_submittable_attribute',
               existing_type=sa.VARCHAR(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_tag', schema=None) as batch_op:
        batch_op.alter_column('user_submittable_attribute',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
